name: SmartSpawner
version: '${version}'
main: github.nighter.smartspawner.SmartSpawner
api-version: '1.20'
authors: [https://github.com/ptthanh02/Smart-Spawner/graphs/contributors]
folia-supported: true
softdepend:
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - ShopGUIPlus
  - zShop
  - Vault
  - Essentials
  - CMI
  - WorldGuard
  - GriefPrevention
  - Lands
  - Towny
  - SimpleClaimSystem
  - SuperiorSkyblock2
  - Multiverse-Core
  - Worlds
  - BlockLocker
commands:
  smartspawner:
    description: Main command for SmartSpawner plugin
    aliases: [ss, spawner]
    permission: smartspawner.reload

permissions:
  smartspawner.*:
    description: Grants access to all SmartSpawner permissions
    default: op
    children:
      smartspawner.reload: true
      smartspawner.give: true
      smartspawner.stack: true
      smartspawner.changetype: true
      smartspawner.break: true
      smartspawner.sellall: true
      smartspawner.list: true
      smartspawner.hologram: true
  smartspawner.reload:
    description: Permission to reload SmartSpawner plugin
    default: op
  smartspawner.give:
    description: Allow giving spawners to yourself or other players
    default: op
  smartspawner.list:
    description: Allow viewing list of spawners and teleporting to them
    default: op
  smartspawner.hologram:
    description: Allow toggling hologram for spawners
    default: op
  smartspawner.changetype:
    description: Allow changing spawner type with spawn egg
    default: op
  smartspawner.stack:
    description: Allow stacking spawners
    default: true
  smartspawner.break:
    description: Allow breaking spawners
    default: true
  smartspawner.sellall:
    description: Allow selling items in spawner storage GUI
    default: true